//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KZDev.PerfUtils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KZDev.PerfUtils.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is too short..
        /// </summary>
        internal static string Arg_DestinationTooShort {
            get {
                return ResourceManager.GetString("Arg_DestinationTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string Arg_IndexMustBeLessException {
            get {
                return ResourceManager.GetString("Arg_IndexMustBeLessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than or equal to the size of the collection..
        /// </summary>
        internal static string Arg_IndexMustBeLessOrEqualException {
            get {
                return ResourceManager.GetString("Arg_IndexMustBeLessOrEqualException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string Arg_InvalidOffsetLength {
            get {
                return ResourceManager.GetString("Arg_InvalidOffsetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid seek origin..
        /// </summary>
        internal static string Arg_InvalidSeekOrigin {
            get {
                return ResourceManager.GetString("Arg_InvalidSeekOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string Arg_OutOfRangeMinValue {
            get {
                return ResourceManager.GetString("Arg_OutOfRangeMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string Arg_OutOfRangeNeedBetween {
            get {
                return ResourceManager.GetString("Arg_OutOfRangeNeedBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to zero..
        /// </summary>
        internal static string Arg_OutOfRangeNonNegNum {
            get {
                return ResourceManager.GetString("Arg_OutOfRangeNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested capacity is less than current size..
        /// </summary>
        internal static string Arg_OutOfRangeSmallCapacity {
            get {
                return ResourceManager.GetString("Arg_OutOfRangeSmallCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream length must be non-negative and less than int.MaxValue..
        /// </summary>
        internal static string Arg_OutOfRangeStreamLength {
            get {
                return ResourceManager.GetString("Arg_OutOfRangeStreamLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} global default settings can not be updated after the first {0} instance has been created..
        /// </summary>
        internal static string InvalidOperation_GlobalSettingsCantBeUpdated {
            get {
                return ResourceManager.GetString("InvalidOperation_GlobalSettingsCantBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The memory segment is native memory; a reference byte array is not available..
        /// </summary>
        internal static string InvalidOperation_MemorySegmentIsNative {
            get {
                return ResourceManager.GetString("InvalidOperation_MemorySegmentIsNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed Stream..
        /// </summary>
        internal static string InvalidOperation_StreamClosed {
            get {
                return ResourceManager.GetString("InvalidOperation_StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to move the position before the beginning of the stream..
        /// </summary>
        internal static string IO_SeekBeforeBegin {
            get {
                return ResourceManager.GetString("IO_SeekBeforeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream was too long..
        /// </summary>
        internal static string IO_StreamTooLong {
            get {
                return ResourceManager.GetString("IO_StreamTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is not supported with {0} mode MemoryStreamSlim instances..
        /// </summary>
        internal static string NotSupported_InvalidModeStreamStream {
            get {
                return ResourceManager.GetString("NotSupported_InvalidModeStreamStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        internal static string NotSupported_UnwritableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }
    }
}
